//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyers
    {
        public int idBuyer { get; set; }
        public string nameOfOrganization { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public int codeAccount { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
