//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsSales
    {
        public int id { get; set; }
        public int idContract { get; set; }
        public string TypeOfFurniture { get; set; }
        public int count { get; set; }
    
        public virtual Contarcts Contarcts { get; set; }
        public virtual TypesOfFurnitures TypesOfFurnitures { get; set; }
    }
}
