//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contarcts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contarcts()
        {
            this.ContractsSales = new HashSet<ContractsSales>();
        }
    
        public int idContract { get; set; }
        public int idBuyer { get; set; }
        public System.DateTime registrationDate { get; set; }
        public System.DateTime dueDate { get; set; }
        public int order { get; set; }
    
        public virtual Buyers Buyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractsSales> ContractsSales { get; set; }
    }
}
